### ISSUE TITLE
syntax highlighting

### ISSUE THREAD

**Issue by gentunian** [fbaligand/vscode-logstash-editor#1]
hi there, nice extension!

I just discovered this because I was thinking that it may be a good idea and I thought on searching it :)

I was wondering if you are willing to support syntax highlighting. The default .conf syntax highlighting went off after loading the extension. Are you thinking on supporting the default syntax highlighting for .conf files?

nice work.

**Comment by fbaligand** [comment]
Hi,

Nice to see that you appreciate the work ;)

Concerning syntax highlighting, there is already a plugin for that:
https://marketplace.visualstudio.com/items?itemName=RandomChance.logstash

That’s why I didn’t add syntax highlighting.
The two plugins complement each other.

**Comment by gentunian** [comment]
great! didn't know about it. Closing this.
