### ISSUE TITLE
Additional Logstash Conf Files

### ISSUE THREAD

**Issue by TasMot** [fbaligand/vscode-logstash-editor#6]
Hi,
When I used this extension for logstash.yml and pipeline.yml, it was great! However; the system I inherited and don't want to refactor uses a parameter in the pipeline.yml that points to /etc/logstash/conf.d/** for additional configuration files. Each of these is prefixed with a number and suffixed with ".conf". According to the Logstash documentation they are read in numeric order and then earlier config wins if there is a duplicate. 
However; I can't figure out how to use your extension to "work" these files as they don't have one of the fixed names.
I would like to either point to the pipeline.yml and say those are good, or allow me to specify that some arbitrary directory (of my choosing) will contain some Logstash ".conf" files.
Thanks,
Tom

**Comment by fbaligand** [comment]
Hi,

In Visual Studio Code, you can define custom file associations to any language, including Logstash language.
So to answer your need, you can do that: 
- go to "Settings" menu, then go into "Text Editor" section and "Files" sub-section
- click on "Add item" and associate "*.conf" to "logstash" language
- or, to be more precise, associate "**/logstash/conf.d/*.conf" to "logstash" language

**Comment by TasMot** [comment]
Thank You, that worked great....  Tom

**Comment by fbaligand** [comment]
Nice to see that it works great!

Fabien
