### ISSUE TITLE
logstash-editor extension is not found in the Visual Studio Extentions

### ISSUE THREAD

**Issue by tompearson** [fbaligand/vscode-logstash-editor#8]
![image](https://user-images.githubusercontent.com/1223955/231323012-fe535e82-b233-4dc6-a74c-fb2677be849f.png)

Microsoft Visual Studio Community 2019
Version 16.11.26
VisualStudio.16.Release/16.11.26+33529.622
Microsoft .NET Framework
Version 4.8.04084
Installed Version: Community
ASP.NET and Web Tools 2019   16.11.115.10959
ASP.NET and Web Tools 2019
Azure App Service Tools v3.0.0   16.11.115.10959
Azure App Service Tools v3.0.0

**Comment by fbaligand** [comment]
Hi,

Logstash vscode editor is unfortunately a visual studio code extension, not a visual studio extension. 
So it is only available for visual studio code IDE.

it is available on marketplace here:
https://marketplace.visualstudio.com/items?itemName=fbaligand.vscode-logstash-editor
